# Generated by Django 4.1.5 on 2023-01-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_name_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_name',
            old_name='jp',
            new_name='Job_Profile',
        ),
        migrations.RenameField(
            model_name='company_name',
            old_name='tof',
            new_name='Offer_Type',
        ),
        migrations.RenameField(
            model_name='company_name',
            old_name='yr',
            new_name='year',
        ),
    ]
