# Generated by Django 4.1.5 on 2023-01-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_jp_company_name_job_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_name',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
